version: "3.9"

services:

  backend:
    build: .
    container_name: garud_backend
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
    volumes:
      - .:/app
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: garud_elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    restart: always